### ISSUE TITLE
Split providers to its own folder

### ISSUE THREAD

**Issue by harikt** [sergeyklay/php-orm-benchmark#10]
Hi, 

Have you thought of splitting the providers to its own folder and having an independent composer.json file ?

Else I wonder whether the memory consumption of different components by composer autoload have some effect.

**Comment by sergeyklay** [comment]
@harikt 

Hello,

Thank you for the proposal, and for helping make benchmark better. In general I agree with idea of splitting the providers to its own folder. Could you start this work?

**Comment by harikt** [comment]
I have been working on testing with dms. So once I am done with it I can look into splitting it.

**Comment by harikt** [comment]
I have made some progress on https://github.com/sergeyklay/php-orm-benchmark/pull/12 . Let me know if you have any thoughts on the same .
