### ISSUE TITLE
Add Doctrine ORM to the benchmarks?

### ISSUE THREAD

**Issue by javiereguiluz** [sergeyklay/php-orm-benchmark#2]
Thanks for publishing this project! If it's possible, I'd love to see [Doctrine ORM](http://www.doctrine-project.org/projects/orm.html) added to this benchmark. Thanks!

**Comment by theofidry** [comment]
👍  especially since it's by far the most popular ORM...

For the record:

| orm | packagist downloads |
|---|--:|
| CakePHP ORM | 25 129 |
| Eloquent | 3 870 853 |
| Propel 2 | 503 669 |
| Yii framework | 3 925 512 |

And Doctrine: 30 588 730

So let's not miss the kind in the benchmark :)

**Comment by Izopi4a** [comment]
a lot of people will get angry with the results and blame other stuff.
Like everybody knows, benchmarking is everything and it is relevant  99.99% of the cases :D

**Comment by JABirchall** [comment]
I mean, [Laravel bundles Eloquent into the framework](https://github.com/laravel/framework/tree/5.5/src/Illuminate/Database).
That eloquent number is just the standalone ORM installations. with Laraval installs Eloquent would be;

37 227 836 just saying

**Comment by theofidry** [comment]
@JABirchall fair enough. The point though is about not ignoring a major player, not debating who's number one. Just saying.

Thanks @sergeyklay
